import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className='bg-white p-4 shadow-md text-black flex justify-center align-items-center box-shadow-md mb-2rem'>
          <ul className='list-none flex gap-1rem m-0 p-0 '>
            <li className='m-0 '>
              <Link href="/form" className='ml-10 text-black  text-decoration-none hover:text-blue-500 hover:text-decoration-underline hover:font-bold'>Formulaire</Link>
            </li>
            <li className='m-0'>
              <Link href="/posts" className='ml-10 text-black text-decoration-none hover:text-blue-500 hover:text-decoration-underline hover:font-bold'>Posts</Link>
            </li>
            <li className='m-0'>
              <Link href="/users" className='ml-10 text-black text-decoration-none hover:text-blue-500 hover:text-decoration-underline hover:font-bold'>Utilisateurs</Link>
            </li>
            <li className='m-0'>
              <Link href="/comments" className='ml-10 text-black text-decoration-none hover:text-blue-500 hover:text-decoration-underline hover:font-bold'>Commentaires</Link>
            </li>
            <li className='m-0'>
              <Link href="/pages/user" className='ml-10 text-black text-decoration-none hover:text-blue-500 hover:text-decoration-underline hover:font-bold'>test</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
